name: 同步外刊到Obsidian(WebDAV版)

on:
  # 在同步上游仓库工作流完成后运行
  workflow_run:
    workflows: ["同步上游仓库"]
    types:
      - completed
  # 允许手动触发
  workflow_dispatch:

jobs:
  sync-to-webdav:
    runs-on: ubuntu-latest
    # 只有当触发的工作流成功完成时才运行
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      # 检出当前仓库代码（使用稀疏检出策略，只检出必要的目录结构）
      - name: 检出当前仓库
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          sparse-checkout: |
            01_economist
            02_new_yorker
            04_atlantic
            05_wired
          sparse-checkout-cone-mode: true
      
      # 安装WebDAV客户端
      - name: 安装WebDAV客户端
        run: |
          sudo apt-get update
          sudo apt-get install -y davfs2
          sudo mkdir -p /mnt/webdav
          echo "${{ secrets.WEBDAV_HOST }} ${{ secrets.WEBDAV_USERNAME }} ${{ secrets.WEBDAV_PASSWORD }}" | sudo tee /etc/davfs2/secrets > /dev/null
          sudo chmod 600 /etc/davfs2/secrets
      
      # 挂载WebDAV
      - name: 挂载WebDAV
        run: |
          sudo mount -t davfs ${{ secrets.WEBDAV_HOST }} /mnt/webdav -o uid=$(id -u),gid=$(id -g)
          df -h
      
      # 列出目录内容，以便于调试
      - name: 列出目录内容
        run: |
          echo "列出经济学人目录内容："
          ls -la ./01_economist || echo "经济学人目录不存在"
          echo "列出纽约客目录内容："
          ls -la ./02_new_yorker || echo "纽约客目录不存在"
          echo "列出Atlantic目录内容："
          ls -la ./04_atlantic || echo "Atlantic目录不存在"
          echo "列出Wired目录内容："
          ls -la ./05_wired || echo "Wired目录不存在"
      
      # 查找最新的经济学人文件
      - name: 查找最新的经济学人文件
        id: economist
        run: |
          if [ -d "./01_economist" ]; then
            LATEST_ECONOMIST_DIR=$(find ./01_economist -maxdepth 1 -type d -name "te_*" | sort -r | head -n 1)
            echo "latest_dir=$LATEST_ECONOMIST_DIR" >> $GITHUB_OUTPUT
            
            # 从目录名中提取日期（格式如te_2025.04.05）
            if [ -n "$LATEST_ECONOMIST_DIR" ]; then
              DIR_NAME=$(basename "$LATEST_ECONOMIST_DIR")
              ECONOMIST_DATE=$(echo "$DIR_NAME" | sed 's/te_//')
              echo "date=$ECONOMIST_DATE" >> $GITHUB_OUTPUT
              echo "找到最新的经济学人目录: $LATEST_ECONOMIST_DIR，日期: $ECONOMIST_DATE"
            fi
          else
            echo "经济学人目录不存在"
            echo "latest_dir=" >> $GITHUB_OUTPUT
          fi
      
      # 查找最新的纽约客文件
      - name: 查找最新的纽约客文件
        id: newyorker
        run: |
          if [ -d "./02_new_yorker" ]; then
            LATEST_NEWYORKER_DIR=$(find ./02_new_yorker -maxdepth 1 -type d -mindepth 1 -not -path "*/\.*" | sort -r | head -n 1)
            echo "latest_dir=$LATEST_NEWYORKER_DIR" >> $GITHUB_OUTPUT
            
            # 从目录名中提取日期
            if [ -n "$LATEST_NEWYORKER_DIR" ]; then
              DIR_NAME=$(basename "$LATEST_NEWYORKER_DIR")
              echo "date=$DIR_NAME" >> $GITHUB_OUTPUT
              echo "找到最新的纽约客目录: $LATEST_NEWYORKER_DIR，日期: $DIR_NAME"
            fi
          else
            echo "纽约客目录不存在"
            echo "latest_dir=" >> $GITHUB_OUTPUT
          fi
      
      # 同步经济学人到WebDAV
      - name: 同步经济学人到WebDAV
        if: steps.economist.outputs.latest_dir != ''
        run: |
          echo "开始同步经济学人目录: ${{ steps.economist.outputs.latest_dir }}"
          
          if [ -d "${{ steps.economist.outputs.latest_dir }}" ]; then
            # 创建目标目录
            TARGET_DIR="/mnt/webdav/外刊集合/经济学人/${{ steps.economist.outputs.date }}"
            mkdir -p "$TARGET_DIR"
            
            # 只上传PDF文件
            for file in "${{ steps.economist.outputs.latest_dir }}"/*.pdf; do
              if [ -f "$file" ]; then
                echo "正在上传PDF文件: $file 到 $TARGET_DIR/"
                cp "$file" "$TARGET_DIR/"
              fi
            done
            echo "已同步经济学人PDF到WebDAV"
          else
            echo "经济学人目录不存在或为空: ${{ steps.economist.outputs.latest_dir }}"
          fi
      
      # 同步纽约客到WebDAV
      - name: 同步纽约客到WebDAV
        if: steps.newyorker.outputs.latest_dir != ''
        run: |
          if [ -d "${{ steps.newyorker.outputs.latest_dir }}" ]; then
            # 创建目标目录
            TARGET_DIR="/mnt/webdav/外刊集合/纽约客/${{ steps.newyorker.outputs.date }}"
            mkdir -p "$TARGET_DIR"
            
            # 只上传PDF文件
            for file in "${{ steps.newyorker.outputs.latest_dir }}"/*.pdf; do
              if [ -f "$file" ]; then
                echo "正在上传PDF文件: $file 到 $TARGET_DIR/"
                cp "$file" "$TARGET_DIR/"
              fi
            done
            echo "已同步纽约客PDF到WebDAV"
          else
            echo "纽约客目录不存在或为空: ${{ steps.newyorker.outputs.latest_dir }}"
          fi
      
      # 同步The Atlantic到WebDAV
      - name: 同步The Atlantic到WebDAV
        run: |
          if [ -d "./04_atlantic" ]; then
            LATEST_ATLANTIC_DIR=$(find ./04_atlantic -maxdepth 1 -type d -mindepth 1 -not -path "*/\.*" | sort -r | head -n 1)
            if [ -n "$LATEST_ATLANTIC_DIR" ] && [ -d "$LATEST_ATLANTIC_DIR" ]; then
              # 从目录名中提取日期
              DIR_NAME=$(basename "$LATEST_ATLANTIC_DIR")
              ATLANTIC_DATE=$DIR_NAME
              echo "找到最新的大西洋月刊目录: $LATEST_ATLANTIC_DIR，日期: $ATLANTIC_DATE"
              
              # 创建目标目录
              TARGET_DIR="/mnt/webdav/外刊集合/大西洋月刊/$ATLANTIC_DATE"
              mkdir -p "$TARGET_DIR"
              
              # 只上传PDF文件
              for file in "$LATEST_ATLANTIC_DIR"/*.pdf; do
                if [ -f "$file" ]; then
                  echo "正在上传PDF文件: $file 到 $TARGET_DIR/"
                  cp "$file" "$TARGET_DIR/"
                fi
              done
              echo "已同步The Atlantic PDF到WebDAV"
            else
              echo "未找到有效的The Atlantic目录"
            fi
          else
            echo "Atlantic目录不存在"
          fi
      
      # 同步Wired到WebDAV
      - name: 同步Wired到WebDAV
        run: |
          if [ -d "./05_wired" ]; then
            LATEST_WIRED_DIR=$(find ./05_wired -maxdepth 1 -type d -mindepth 1 -not -path "*/\.*" | sort -r | head -n 1)
            if [ -n "$LATEST_WIRED_DIR" ] && [ -d "$LATEST_WIRED_DIR" ]; then
              # 从目录名中提取日期
              DIR_NAME=$(basename "$LATEST_WIRED_DIR")
              WIRED_DATE=$DIR_NAME
              echo "找到最新的连线杂志目录: $LATEST_WIRED_DIR，日期: $WIRED_DATE"
              
              # 创建目标目录
              TARGET_DIR="/mnt/webdav/外刊集合/连线杂志/$WIRED_DATE"
              mkdir -p "$TARGET_DIR"
              
              # 只上传PDF文件
              for file in "$LATEST_WIRED_DIR"/*.pdf; do
                if [ -f "$file" ]; then
                  echo "正在上传PDF文件: $file 到 $TARGET_DIR/"
                  cp "$file" "$TARGET_DIR/"
                fi
              done
              echo "已同步Wired PDF到WebDAV"
            else
              echo "未找到有效的Wired目录"
            fi
          else
            echo "Wired目录不存在"
          fi
      
      # 卸载WebDAV
      - name: 卸载WebDAV
        if: always()
        run: |
          sudo umount /mnt/webdav || echo "卸载WebDAV失败"
